namespace Business_Processes_Automation.DAL.Enums;

public enum ConversationStep
{
    Idle = 0,
    MasterAddingServiceName = 11,
    MasterAddingServiceDuration = 12,
    MasterAddingServicePrice = 13,
    MasterRegisteringFirstName = 20,
    MasterRegisteringLastName = 21,
    MasterRegisteringPhone = 22,
    MasterRegisteringEmail = 23,
    MasterRegisteringTimeZone = 24,
    MasterRegisteringBotLink = 25,
    MasterRegisteringConfirm = 26,
    MasterConfirmingDeleteAccount = 27,
    MasterLinkingEnterCode = 28,
    MasterLinkingEnterBotSlug = 29,
    MasterScheduleMenu = 30,
    MasterEditingWorkHoursPickDay = 31,
    MasterEditingWorkHoursStart = 32,
    MasterEditingWorkHoursEnd = 33,
    MasterEditingBuffer = 34,
    MasterAddingTimeOffMenu = 35,
    MasterAddingTimeOffPickDate = 36,
    MasterAddingTimeOffPickMode = 37,
    MasterAddingTimeOffStartTime = 38,
    MasterAddingTimeOffEndTime = 39,
    MasterDeletingTimeOffPickNumber = 40,
    MasterPostRegisterScheduleOffer = 41,
    MasterScheduleViewMenu = 42,
    MasterViewingAppointmentPickNumber = 43,
    MasterEditingSlotInterval = 44,
    ClientChoosingBookPeriod = 50,
    ClientChoosingBookService = 51,
    ClientChoosingBookSlot = 52,
    ClientConfirmingBooking = 53,
    ClientChoosingBookDate = 54
}
